### ISSUE TITLE
v2.1: Site groups cannot be edited or deleted

### ISSUE THREAD

**Issue by emrikol** [Automattic/syndication#112]
In v2.1 site groups cannot be deleted.  Neither with bulk edit or individual edits.  Either a success message or error message will display, but nothing will change.

**Comment by emgk** [comment]
@emrikol are you still experiencing this issue? I have tested branch 2.1 on my local machine, I didn't face any issue while deleting or editing the site group through the bulk edit or individual edit. no error message appeared, worked fine. 

cc @philipjohn

**Comment by MattGeri** [comment]
I've tried to replicate this issue in an attempt to fix it, but I also cannot reproduce the bug being experienced using the code in the `master` branch.

**Comment by philipjohn** [comment]
Closing given we can't reproduce.
