### ISSUE TITLE
featured image upload pb

### ISSUE THREAD

**Issue by unsruns** [Automattic/syndication#125]
Hello, 
First of all, thank you for this plugin its awesome, but when I add a post,  the featured image didn't uploaded on the remote wordpress site.

thanks

**Comment by philipjohn** [comment]
Hi @unsruns - what steps have you taken to try and debug this so far?

**Comment by chetansatasiya** [comment]
Hi @philipjohn I have tested this issue and It seems that I am not able to replicate this issue and it's working fine on my end.

**Comment by philipjohn** [comment]
Thanks @chetansatasiya - will close this but @unsruns can report again some detailed reproduction steps if this is still an issue.
