### ISSUE TITLE
Pull: Individual Cron Jobs for each site

### ISSUE THREAD

**Issue by mjangda** [Automattic/syndication#19]
Instead of a single cron entry to handle all pull endpoints, we should explore having distinct ones for each so that we can more run in parallel.

**Comment by tott** [comment]
Looking at the way WP cronjobs work I'm not sure if simply adding distinct cron entries per pull endpoint will be sufficient to allow parallel execution of pull requests.  wp-cron implements a locking mechanism that tries to run only a single cron job at a time. 

The closest to parallel approach I would see here is to create a separate cronjob per site which will run at different intervals. This will not provide parallel execution but spreads the different calls throughout the defined pull interval and will provide some kind of semi parallel execution. When the previous cronjob is still executed, it will allow starting a new pull action if the previous one takes more than WP_CRON_LOCK_TIMEOUT ( 60 seconds ). 

It would be great if you could add some more insights on what you had in mind.

**Comment by joshbetz** [comment]
I think we can start by just creating distinct jobs for each pull endpoint. As long as it doesn't break anything that should be fine. At least WordPress.com will be able to run them in parallel.

**Comment by tott** [comment]
Ok, we'll get this implemented as you suggested then
