### ISSUE TITLE
Auto retry

### ISSUE THREAD

**Issue by joshbetz** [Automattic/syndication#45]
A better way to find and retry failed syndications.

Failures will happen, but Syndication stores them in a weird way that isn't easy to surface. You have to run through them all to find failures. A cron job that finds those and retries them would be ideal.

props @nickdaugherty

**Comment by joshbetz** [comment]
The logging framework looks cool. I guess the next step is to automatically retry (or disable on too many failures).

**Comment by tott** [comment]
Great, with this in place we can now create a nice dashboard, notifications and also the automatic reaction to failures and such
