### ISSUE TITLE
Improve efficiency

### ISSUE THREAD

**Issue by joshbetz** [Automattic/syndication#47]
For big syndication jobs, we spend a lot of time clearing and priming caches. Let's treat it like an import and wait until the end to clear any caches.

**Comment by tott** [comment]
Hi @joshbetz do you have some insights what this refers to. I checked the codebase and can't see any particular places where cache clearing or priming would happen. 

The only direct interaction with object cache i see is in stop_the_insanity()

**Comment by joshbetz** [comment]
There aren't any explicit interactions in the syndication code. This refers to the caching that is happening automatically in core WordPress. During imports, various caches are disabled so the imported posts are never added to the object cache in the first place. Syndication is essentially an import so we should probably skip adding anything to the object cache while posts are being added.

Does that make sense?

**Comment by tott** [comment]
That makes sense. So you basically want to run the syndication with WP_IMPORTING = true and later on run one function that will rebuild / invalidate the required caches? That's doable.

**Comment by joshbetz** [comment]
Essentially, yep!
