### ISSUE TITLE
Syndicate Author data

### ISSUE THREAD

**Issue by banderon** [Automattic/syndication#61]
Currently, author data is not syndicated; whatever account is used for syndication on the child site is what is used to publish the syndicated post. Author data should be pushed out as well.

**Comment by joshbetz** [comment]
We can (maybe) do this for push syndication if author creation is turned on. If it's not, there's not much we can do here.

**Comment by banderon** [comment]
Or if the author already exists on the child site(s), which was the use case in which this came up. Can't the author ID/user be pushed out as well?

**Comment by joshbetz** [comment]
We can't depend on the user ID to be the same across sites.

**Comment by drapetomaniac** [comment]
joshbetz How is author creation turned on or off?  I don't see that setting anywhere.

When you say user id, is that the id number or user_login?

**Comment by drapetomaniac** [comment]
We've been talking about this issue for a year or more with Automattic and are trying to contribute internal resources to the issue, if it's the same issue we've been seeing.

I'm still not clear on what turns on or off "user creation."

It does seem, however, that a variation of the Bulk Administration plugin functionality could serve up a dashboard that allows for a type of "synching" to verify the user exists between sites. If it's identified as properly acknowledged and synched then it will syndicate under that author name if pushed/pulled.

A soft safeguard could be put in place to indicate when you're about to syndicate a story whether or not the author is "new" (or unsynched).

Does this seem like a reasonable approach?

**Comment by joshbetz** [comment]
@drapetomaniac For example, we can't add users to sites on WordPress.com via Syndication.

**Comment by drapetomaniac** [comment]
@joshbetz But they can be replicated via Bulk Administration at the multi-site level, correct?

**Comment by emrikol** [comment]
Author creation is out of scope for v1 and v2 of the plugin.  The `syn_pull_new_post` filter can be used to map syndicated content authors to current site authors or to create new authors.  It would be a good candidate as an add-on feature plugin for Syndication.
