### ISSUE TITLE
Add a nice dashicon

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/syndication#65]
The current standard "posts" icon is a bit sad. :disappointed: 

If we go for something from the existing dashicons, the most appropriate might be [dashicons-rss](https://developer.wordpress.org/resource/dashicons/#rss), but it might be nice to get creative.

**Comment by norcross** [comment]
fixed via 9aec9c309513ce5cde52ea203f4fb5ecd808c962

**Comment by emrikol** [comment]
Fixed with PR #91
