### ISSUE TITLE
Need multiple Publishers

### ISSUE THREAD

**Issue by drapetomaniac** [Automattic/syndication#74]
Right now, we have an author "Bill."  Bill can't log in to syndicate his own stories for physical reasons, so we have Larry log in for him.  Larry's credentials are set on the settings for transport type credentials on Sites /wp-admin/edit.php?post_type=syn_site

We also have sites where Bill and Bob are publishing and Lynda might be the one responsible for syndicating (and Larry might while she's on vacation).  We need both authors to be shown on the child site.  So, we need multiple author and publisher capability.  We believe Issue #61 might address multiple authors, but also need the multiple publishers, which is what this issue is for.

**Comment by joshbetz** [comment]
Why is it significant that there are multiple publishers? Is that used anywhere?

**Comment by drapetomaniac** [comment]
It's used in multiple production sites.  My understanding is that one person can be the publisher listed in that Site setting and only one person can log in to syndicate.  Those two privileges have to be the same person.

If that's true, even in the smallest publishing house, this would require sharing logins or changing the setting whenever someone is out sick or on vacation.  In a larger publishing house, such as our own and others I have worked in, it's typical to have more than one single person have that responsibility.

**Comment by joshbetz** [comment]
I think there's some confusion here. Any editor or admin should be able to manage syndication jobs.

**Comment by drapetomaniac** [comment]
I'm confirming functionality. I just had an editor try to syndicate with REST credentials created under my name, and it didn't work for her. She's an editor. I'm going to try to escalate her to admin tomorrow and try again.

**Comment by drapetomaniac** [comment]
This doesn't appear to be an issue. We got it to work today. It didn't work as Editor, but the button also didn't show, which appears to be a temporary issue.
