### ISSUE TITLE
Parse Error on install and activation

### ISSUE THREAD

**Issue by RonR-WebDesign** [Automattic/syndication#81]
Parse error: syntax error, unexpected T_FUNCTION in /home/content/35/8172135/html/wp-content/plugins/syndication-master/includes/class-syndication-logger-viewer.php on line 154

**Comment by allan23** [comment]
I can confirm this issue on a PHP 5.3 powered site.

**Comment by joshbetz** [comment]
This is an issue with PHP 5.3 and below. Since this plugin only supports PHP 5.4+, I'm going to close this.
