### ISSUE TITLE
Pull Now timeouts

### ISSUE THREAD

**Issue by stephenharris** [Automattic/syndication#87]
If there are sufficient number of blogs then clicking 'Pull Now' will cause a white screen. 

This happens because the page resulting page request triggers pulling of the all sites (rather than starting a background process to pull the data). 

The number of sites required to reproduce this will obviously vary, but I've seen it with 71 blogs syndicated. 

Ideally 'pull now' should spawn a request independent of the user's one so there is no impact on the user. That would allow the timeout limit to be extended when pulling content. 

I'm holding out on submitting a PR because I'm not sure what the status of https://github.com/Automattic/syndication/pull/84 is - and whether I should fork Adam's copy (if indeed its still a valid issue on his version).

**Comment by emrikol** [comment]
PR #96 updated this to set up a cron event when using "Pull Now" so that it won't block the admin.
