### ISSUE TITLE
Save Changes & Pull Now do the same thing

### ISSUE THREAD

**Issue by stephenharris** [Automattic/syndication#88]
This is a minor UX issue, but clicking 'Pull now' updates the site settings, and vice versa.

I realise that if you update the polling interval, then it might b necessary to reset all the jobs and thus trigger a new pull request, but its odd if you pull now and find your settings have been changed. 

As per https://github.com/Automattic/syndication/issues/87 I think Pull Now should be separated entirely from the user's web request, but if not I think it's a more honest UI to merge the buttons into 'Save Changes & Pull Now'

**Comment by emrikol** [comment]
This has been modified to "Pull Now & Save Changes" in v2.1 with PR #96 

If you'd like to submit a PR for v2.0 to merge the buttons, I'd be happy to take a look at it

**Comment by emrikol** [comment]
Closing this in favor of the update in v2.1
